[package]
name = "arena_assist"
version = "0.1.0"
authors = ["corey <wilso.core@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
